import type { Mission } from "./types";
import { fc, line, point, poly } from "./geo";

export const MISSIONS: Mission[] = [
  {
    id: "kaziranga",
    code: "KS-FL-07",
    title: "Kaziranga sub-canopy flood",
    region: "Assam · Brahmaputra",
    problem: "Optical sensors see only monsoon cloud. Villages under forest stay unmapped.",
    agent: "kaal_radar",
    secondaryAgents: ["sparsh_grounding", "bhoomi_rakshak", "surya_caption"],
    center: [26.62, 93.35],
    zoom: 11,
    gsdM: 8,
    mapMode: "sar",
    swipeEnabled: false,
    landcover: "flood_canopy",
    predictedClass: "subcanopy_inundation",
    samples: [
      { lang: "en", text: "Map flood water under tree canopy in Kaziranga" },
      { lang: "hi", text: "काजीरंगा में पेड़ों के नीचे बाढ़ का पानी दिखाओ" },
      { lang: "as", text: "কাজিৰঙাত গছৰ তলৰ বানপানী দেখুৱাওক" },
    ],
    geojson: fc([
      poly(
        [
          [93.12, 26.5],
          [93.28, 26.47],
          [93.48, 26.5],
          [93.62, 26.55],
          [93.66, 26.66],
          [93.52, 26.74],
          [93.32, 26.76],
          [93.16, 26.7],
          [93.08, 26.6],
        ],
        { kind: "flood", name: "Open water (specular SAR)", value: 612, unit: "km²" },
      ),
      poly(
        [
          [93.22, 26.56],
          [93.38, 26.54],
          [93.5, 26.58],
          [93.48, 26.66],
          [93.34, 26.68],
          [93.22, 26.64],
        ],
        {
          kind: "canopy_flood",
          name: "Sub-canopy inundation (Pd double-bounce)",
          value: 312,
          unit: "km²",
        },
      ),
      line(
        [
          [93.05, 26.52],
          [93.18, 26.55],
          [93.32, 26.57],
          [93.48, 26.58],
          [93.64, 26.6],
        ],
        { kind: "road", name: "NH-37", value: 18.4, unit: "km inundated" },
      ),
      point([93.4, 26.58], {
        kind: "village",
        name: "Kohora range",
        value: 14,
        unit: "hamlets",
      }),
      point([93.24, 26.61], {
        kind: "village",
        name: "Bagori range",
        value: 11,
        unit: "hamlets",
      }),
    ]),
    geocp: {
      ece: 0.024,
      coverage: 0.955,
      moranI: 0.47,
      interval: [0.81, 0.98],
      zone: "Assam floodplain forest",
    },
    answer:
      "RISAT C-band sees through the cloud deck. Double-bounce Pd spikes map 312 km² of water under canopy plus 612 km² of open flood. NH-37 is overtopped for 18.4 km between Kohora and Bagori.",
    vqa: {
      question: "Is there flood water under the forest canopy?",
      answer: "Yes. 312 km² of sub-canopy inundation with Pd dominance (0.58) and RVoG hv ≈ 18 m.",
      confidence: 0.972,
    },
    report: {
      t1: "Kaziranga and the south bank of the Brahmaputra are inundated under 100% cloud. Radar confirms 924 km² of water, of which 312 km² sits under tree canopy that optical satellites cannot see.",
      t2: "NH-37 is overtopped for 18.4 km. 25 hamlets in Kohora and Bagori ranges are isolated. Recommend NDMA SOP: boat staging at Bokakhat, halt eastbound traffic at Nagaon, airdrop to elevated chaporis. Elephant corridors along the park edge are also flooded — wildlife displacement likely onto the highway berm.",
      t3: "Kaal-Radar inversion: T3 deoriented, helix Ph = 0.03, volume Pv from 15/8 T33, double-bounce Pd dominates over surface inside the forest mask. RVoG coherence γ(w) = 0.61, hv = Δφ / kz ≈ 18.4 m. OSWI fused MNDWI×σ⁰VV flags open water; Pd residual after volume removal flags trunk-water dihedrals. Vivek-Causal not required — monsoon hydrograph is the parent cause.",
      t4: [
        { label: "Open water", value: "612 km²" },
        { label: "Sub-canopy water", value: "312 km²" },
        { label: "NH-37 overtopped", value: "18.4 km" },
        { label: "Pd / Pv ratio", value: "2.07" },
        { label: "Cloud cover (optical)", value: "100%" },
      ],
    },
    ndmaSop:
      "[NDMA-SOP-2026/AS-07] BOKAKHAT SECTOR COMMAND\n1. Stage 14 motorized inflatable boats at Bokakhat Sub-Divisional HQ.\n2. Impose immediate traffic diversion on NH-37 between Kohora (KM 142) and Bagori (KM 160) — flood overtopping 18.4 km.\n3. Establish elevated relief camp on Diffaloo Chapori for 25 marooned hamlets.\n4. Forest Guard anti-poaching patrol activated for flood-migrating wildlife across southern highway berm.\n5. Air Force ALH Dhruv helicopters on standby at Tezpur AFS for winch rescue operations.",
  },
  {
    id: "joshimath",
    code: "JH-DN-02",
    title: "Joshimath crustal slip",
    region: "Uttarakhand · Chamoli",
    problem: "Optical scenes look unchanged while buildings crack. Motion is millimetric.",
    agent: "ratna_garbha",
    secondaryAgents: ["samay_change", "sparsh_grounding", "surya_caption"],
    center: [30.555, 79.565],
    zoom: 15,
    gsdM: 3,
    mapMode: "sar",
    swipeEnabled: true,
    beforeLabel: "T0 · 2022-10",
    afterLabel: "T1 · 2023-01",
    landcover: "mountain_town",
    predictedClass: "built_up",
    slopeOverride: 18.6,
    samples: [
      { lang: "en", text: "Detect land sinking at Joshimath" },
      { lang: "hi", text: "जोशीमठ में भूमि धंसाव कितना है?" },
      { lang: "ne", text: "जोशीमठमा जमिन भास्सिएको छ कि?" },
    ],
    geojson: fc([
      poly(
        [
          [79.555, 30.549],
          [79.562, 30.548],
          [79.566, 30.552],
          [79.561, 30.556],
          [79.554, 30.554],
        ],
        { kind: "subsidence", name: "Manohar Bagh · 4.1 mm/mo", value: 4.1, unit: "mm/mo" },
      ),
      poly(
        [
          [79.562, 30.553],
          [79.569, 30.552],
          [79.572, 30.557],
          [79.566, 30.56],
          [79.56, 30.557],
        ],
        { kind: "subsidence", name: "Singhdhar · 2.8 mm/mo", value: 2.8, unit: "mm/mo" },
      ),
      poly(
        [
          [79.568, 30.548],
          [79.575, 30.547],
          [79.577, 30.552],
          [79.571, 30.554],
        ],
        { kind: "subsidence", name: "Marwari · 2.2 mm/mo", value: 2.2, unit: "mm/mo" },
      ),
      line(
        [
          [79.55, 30.545],
          [79.56, 30.55],
          [79.57, 30.555],
          [79.58, 30.56],
        ],
        { kind: "road", name: "NH-7 / Badrinath Road", value: 0, unit: "km" },
      ),
    ]),
    geocp: {
      ece: 0.019,
      coverage: 0.968,
      moranI: 0.33,
      interval: [1.6, 3.1],
      zone: "Western Himalaya · seismic",
    },
    answer:
      "DInSAR LOS displacement peaks at 4.1 mm/month in Manohar Bagh. 214 structures sit inside the 2 mm/month contour. Optical pixels are unchanged — the signal is phase, not radiance.",
    vqa: {
      question: "Is Joshimath sinking?",
      answer: "Yes. Three wards show coherent LOS subsidence of 2.2–4.1 mm/month (coherence 0.72).",
      confidence: 0.96,
    },
    report: {
      t1: "Joshimath is sliding. Radar phase, not photographs, shows 2.2 to 4.1 mm of line-of-sight subsidence per month across Manohar Bagh, Singhdhar and Marwari — weeks of warning before visible cracks.",
      t2: "214 buildings intersect the 2 mm/month contour. NH-7 (Badrinath Road) crosses the Singhdhar lobe. Recommend: vacate red-tagged houses in Manohar Bagh, survey the JP hydel drain, freeze new cutting on the toe slope, and keep a 24 h geodetic prism on the temple terrace.",
      t3: "Ratna-Garbha unwraps a 12-day RISAT/Sentinel-1 pair. After topographic phase removal with CartoDEM, residual φ maps to δr = λ φ / 4π. Mean velocity 2.4 mm/mo; peak 4.1. Coherence 0.72 rules out decorrelated snow. Samay-Change optical residual is < 0.4% — Vivek-Causal attributes motion to toe erosion + drain saturation, not a new tectonic event.",
      t4: [
        { label: "Peak LOS", value: "4.1 mm/mo" },
        { label: "Ward mean", value: "2.4 mm/mo" },
        { label: "Coherence γ", value: "0.72" },
        { label: "Structures in 2 mm contour", value: "214" },
        { label: "Slope", value: "18.6°" },
      ],
    },
    ndmaSop:
      "[SDMA-UK-SOP-2026/CH-02] CHAMOLI DISTRICT EMERGENCY COMMAND\n1. Immediate structural red-tagging and evacuation of 214 high-risk residences in Manohar Bagh and Singhdhar wards.\n2. Total moratorium on subsurface excavation, slope toe cutting, and heavy construction on the Marwari slope.\n3. Install automated geodetic laser prisms and continuous tiltmeters on temple terrace and NH-7 bridge.\n4. Route subterranean drainage water away from saturated toe faults via pre-cast collector flumes.\n5. Keep SDRF search-and-rescue teams stationed at Joshimath ITBP Barracks for immediate deployment.",
  },
  {
    id: "chambal",
    code: "CB-CA-11",
    title: "Chambal harvest vs forest",
    region: "Madhya Pradesh / Rajasthan",
    problem: "Pixel differencing flags wheat harvest as illegal deforestation.",
    agent: "vivek_causal",
    secondaryAgents: ["samay_change", "bhoomi_optical", "surya_caption"],
    center: [26.48, 78.15],
    zoom: 11,
    gsdM: 10,
    mapMode: "optical",
    swipeEnabled: true,
    beforeLabel: "Rabi peak · Feb",
    afterLabel: "Post-harvest · Apr",
    landcover: "ravine_agri",
    predictedClass: "harvested_cropland",
    samples: [
      { lang: "en", text: "Is this deforestation or harvest along the Chambal?" },
      { lang: "hi", text: "चंबल के किनारे यह जंगल कटाई है या फसल?" },
      { lang: "mr", text: "चंबळ काठावरील बदल वृक्षतोड आहे की कापणी?" },
    ],
    geojson: fc([
      poly(
        [
          [78.02, 26.42],
          [78.18, 26.4],
          [78.28, 26.46],
          [78.2, 26.54],
          [78.06, 26.52],
        ],
        { kind: "harvest", name: "Rabi wheat harvest (false alarm)", value: 4372, unit: "ha" },
      ),
      poly(
        [
          [78.22, 26.5],
          [78.3, 26.49],
          [78.34, 26.54],
          [78.28, 26.57],
          [78.22, 26.55],
        ],
        { kind: "deforest", name: "Persistent forest loss", value: 438, unit: "ha" },
      ),
      line(
        [
          [77.98, 26.5],
          [78.1, 26.47],
          [78.22, 26.48],
          [78.36, 26.52],
        ],
        { kind: "road", name: "Chambal ravine edge", value: 0, unit: "" },
      ),
    ]),
    geocp: {
      ece: 0.022,
      coverage: 0.957,
      moranI: 0.29,
      interval: [0.72, 0.94],
      zone: "Central plateau · Chambal",
    },
    answer:
      "Of 4,810 ha of NDVI drop, 4,372 ha (91%) is Rabi wheat harvest conditioned on the crop calendar. 438 ha is persistent woody loss that survives the do-operator and should be field-verified.",
    vqa: {
      question: "Is the NDVI drop illegal deforestation?",
      answer: "Mostly no. 91% is harvest (do(calendar)=Rabi). 9% remains as forest-loss residual.",
      confidence: 0.948,
    },
    report: {
      t1: "A naive change mask over the Chambal ravines screams deforestation. After Pearl do-calculus on the crop calendar, 91% of the NDVI drop is wheat leaving the field. 438 ha of woody loss remains.",
      t2: "Do not raise an SDMA forest offence on the 4,372 ha harvest polygon. Dispatch a beat guard only to the 438 ha persistent-loss patch on the northern ravine lip. Kharif sowing is six weeks out — the harvest class will green up; the woody class will not.",
      t3: "Samay-Change F1 on the raw mask is high but causally confounded. Vivek-Causal SCM: season → NDVI, harvest → NDVI, illegal felling → NDVI. P(ΔY | do(harvest), calendar=Rabi) explains the large polygon. The residual after intervening on harvest is the 438 ha forest node. MESMA soil fraction jumps from 0.18 to 0.44 on harvest; it stays veg-dominated on the forest residual.",
      t4: [
        { label: "NDVI-drop area", value: "4,810 ha" },
        { label: "Harvest (suppressed)", value: "4,372 ha · 91%" },
        { label: "Persistent forest loss", value: "438 ha · 9%" },
        { label: "False-alarm cut", value: "94.8%" },
        { label: "Calendar", value: "Rabi wheat · Apr" },
      ],
    },
    ndmaSop:
      "[FOREST-DEPT-SOP-2026/MP-11] CHAMBAL SANCTUARY BEAT PROTOCOL\n1. STAND DOWN tactical forest offence alert on 4,372 ha agricultural plain (verified Rabi wheat harvest; false alarm suppressed by Vivek-Causal).\n2. Dispatch 2 beat guard patrol teams exclusively to the 438 ha northern ravine lip exhibiting persistent woody loss.\n3. Coordinate with District Collectorate for drone photogrammetry over active land-clearing coordinates (26.54°N, 78.28°E).\n4. Notify local revenue officials that harvest green-up is projected within 6 weeks for Kharif prep.",
  },
  {
    id: "kuttanad",
    code: "KL-HW-04",
    title: "Kuttanad highway inundation",
    region: "Kerala · Alappuzha",
    problem: "Below-MSL paddy and NH-66 flood together. Operators need vernacular answers.",
    agent: "bhoomi_rakshak",
    secondaryAgents: ["kaal_radar", "sparsh_grounding", "surya_caption"],
    center: [9.5, 76.45],
    zoom: 11,
    gsdM: 10,
    mapMode: "sar",
    swipeEnabled: false,
    landcover: "kuttanad",
    predictedClass: "standing_water",
    slopeOverride: 0.3,
    samples: [
      { lang: "hi", text: "क्या बाढ़ का पानी हाईवे तक पहुँच गया है?" },
      { lang: "ml", text: "ഹൈവേ വെള്ളത്തിനടിയിലായോ?" },
      { lang: "en", text: "Has flood water reached the highway?" },
    ],
    geojson: fc([
      poly(
        [
          [76.32, 9.38],
          [76.48, 9.36],
          [76.58, 9.44],
          [76.52, 9.58],
          [76.38, 9.6],
          [76.28, 9.5],
        ],
        { kind: "flood", name: "Kuttanad padasekharam inundation", value: 186, unit: "km²" },
      ),
      line(
        [
          [76.3, 9.42],
          [76.38, 9.46],
          [76.46, 9.5],
          [76.54, 9.54],
          [76.6, 9.58],
        ],
        { kind: "road", name: "NH-66", value: 7.6, unit: "km overtopped" },
      ),
      point([76.33, 9.5], { kind: "village", name: "Kuttanad taluk", value: 22, unit: "wards" }),
      point([76.52, 9.48], { kind: "village", name: "Alappuzha approach", value: 6, unit: "wards" }),
    ]),
    geocp: {
      ece: 0.018,
      coverage: 0.971,
      moranI: 0.52,
      interval: [0.88, 0.99],
      zone: "Kerala backwater · below MSL",
    },
    answer:
      "हाँ. NH-66 के 7.6 किमी खंड बाढ़ के पानी में हैं. कुट्टनाड के 186 वर्ग किमी धान के खेत जलमग्न हैं — यह क्षेत्र समुद्र तल से नीचे है, ढलान 0.3°.",
    vqa: {
      question: "क्या बाढ़ का पानी हाईवे तक पहुँच गया है?",
      answer: "हाँ. NH-66 overtopped for 7.6 km. 22 wards isolated. SOP: ferry from Alappuzha jetty.",
      confidence: 0.97,
    },
    report: {
      t1: "Yes — flood water has reached the highway. NH-66 is overtopped for 7.6 km across the Kuttanad padasekharams, which already sit below mean sea level.",
      t2: "22 wards are isolated. NDMA SOP: close NH-66 between Kommady and Ambalappuzha, stage IRBN boats at Punnamada, keep medical boats on the AC Canal, and do not pump outward until the Thottappally spillway is at free flow. Power isolation on the submerged 11 kV spurs.",
      t3: "Bhoomi-Rakshak intersects the OSWI mask with the Bhuvan road graph. Slope 0.3° satisfies the hydrodynamic postulate (standing water legal). σ⁰VV = −19.8 dB (specular). Dharma-Chakra passes all four gates. Bhasha-Brahmand retained the toponyms Kuttanad, taluk, nullah and the query language.",
      t4: [
        { label: "Highway overtopped", value: "7.6 km · NH-66" },
        { label: "Inundated paddy", value: "186 km²" },
        { label: "Elevation", value: "−1.2 to 0.4 m MSL" },
        { label: "Slope", value: "0.3°" },
        { label: "Voice latency", value: "< 350 ms" },
      ],
    },
    ndmaSop:
      "[NDMA-SOP-2026/KL-04] ALAPPUZHA DISASTER MANAGEMENT CELL\n1. Close NH-66 between Kommady and Ambalappuzha — overtopped 7.6 km.\n2. Deploy 18 Kerala Police IRBN water taxis and rescue barges from Alappuzha jetty to evacuate 22 isolated padasekharam wards.\n3. Activate emergency medical boat service along the AC Canal corridor.\n4. De-energize submerged 11 kV KSEB distribution transformers across inundated polders.\n5. Open Thottappally spillway gates to full discharge capacity during low tide window to drain backwater flood pulse.",
  },
  {
    id: "sundarbans",
    code: "SB-MG-09",
    title: "Sundarbans Mangrove Loss & Surge",
    region: "West Bengal · Bay of Bengal",
    problem: "Cyclonic storm surges and saline intrusion breaching embankments and destroying mangrove canopy.",
    agent: "samay_change",
    secondaryAgents: ["sparsh_grounding", "surya_caption", "bhoomi_rakshak"],
    center: [21.95, 88.85],
    zoom: 11,
    gsdM: 10,
    mapMode: "sar",
    swipeEnabled: true,
    beforeLabel: "Pre-Cyclone Coherence (0.74)",
    afterLabel: "Post-Surge Inundation Decay (0.28)",
    landcover: "mangrove_delta",
    predictedClass: "mangrove_dieback",
    slopeOverride: 0.4,
    samples: [
      { lang: "en", text: "Map mangrove canopy loss and saline breach in Sundarbans" },
      { lang: "bn", text: "সুন্দরবনে ঘূর্ণিঝড় পরবর্তী ম্যানগ্রোভ ক্ষয় এবং বাঁধের ভাঙন চিহ্নিত করুন" },
      { lang: "hi", text: "सुंदरबन में चक्रवाती कटाव और मैंग्रोव विनाश दिखाओ" },
    ],
    geojson: fc([
      poly(
        [
          [88.75, 21.85],
          [88.95, 21.82],
          [89.05, 21.95],
          [88.98, 22.08],
          [88.78, 22.05],
        ],
        { kind: "mangrove_loss", name: "Canopy coherence loss", value: 142, unit: "km²" },
      ),
      poly(
        [
          [88.82, 21.92],
          [88.92, 21.9],
          [88.96, 21.98],
          [88.85, 22.0],
        ],
        { kind: "flood", name: "Saline tidal inundation", value: 58, unit: "km²" },
      ),
      line(
        [
          [88.76, 21.96],
          [88.84, 21.98],
          [88.92, 22.02],
        ],
        { kind: "road", name: "Kalindi-Raimangal Embankment", value: 12.4, unit: "km breached" },
      ),
      point([88.8, 22.02], { kind: "village", name: "Gosaba Block", value: 18, unit: "mouzas" }),
      point([88.62, 21.95], { kind: "village", name: "Kultali Delta", value: 14, unit: "mouzas" }),
    ]),
    geocp: {
      ece: 0.021,
      coverage: 0.965,
      moranI: 0.51,
      interval: [0.82, 0.98],
      zone: "Ganges-Brahmaputra Delta · Tidal",
    },
    answer:
      "NISAR L-band polarimetry confirms 142 km² of mangrove canopy degradation. 12.4 km of coastal embankment is breached along the Gosaba-Kultali tidal front with 58 km² saline ingress.",
    vqa: {
      question: "Is there critical embankment breach and mangrove dieback?",
      answer: "Yes. 142 km² canopy degradation and 12.4 km embankment breach detected via coherence decay.",
      confidence: 0.968,
    },
    report: {
      t1: "Sundarbans coastal delta barrier has suffered severe cyclonic storm surge damage. 142 km² of mangrove bio-shield canopy degraded, and 12.4 km of mud embankments have breached.",
      t2: "NDMA SOP: Deploy West Bengal Irrigation & Waterways rapid geotextile bag reinforcement to Gosaba and Kultali blocks. Halts tidal ingress into agricultural freshwater ponds before spring tide.",
      t3: "Samay-Change bi-temporal coherence analysis: γ drops from 0.74 to 0.28 across damaged mangrove tracts. Yamaguchi volume scattering Pv drops 43%, surface scattering Ps spikes due to standing saline water. Slope 0.4° hydrodynamically admissible.",
      t4: [
        { label: "Canopy Degraded", value: "142 km²" },
        { label: "Saline Ingress", value: "58 km²" },
        { label: "Embankment Breach", value: "12.4 km" },
        { label: "Coherence Drop", value: "-62%" },
        { label: "Vulnerability", value: "Severe" },
      ],
    },
    ndmaSop:
      "[NDMA-SOP-2026/WB-09] SUNDARBANS DISASTER MANAGEMENT AUTHORITY\n1. Mobilize geotextile sandbag barges to plug 12.4 km breaches on the Kalindi and Raimangal river dykes.\n2. Evacuate 32 low-lying mouzas in Gosaba and Kultali to elevated Multipurpose Cyclone Shelters (MCS).\n3. Distribute portable water desalinisation units to prevent waterborne cholera outbreaks in saline inundated zones.\n4. Close Sundarbans Tiger Reserve core channels to civilian trawlers during emergency response.",
  },
  {
    id: "lhonak_glof",
    code: "LD-GL-05",
    title: "South Lhonak Glacial Lake Breach",
    region: "Sikkim Himalaya · Teesta Basin",
    problem: "Sudden expansion of moraine-dammed proglacial lake risking catastrophic flash flood downstream.",
    agent: "bhoomi_rakshak",
    secondaryAgents: ["kaal_radar", "ratna_garbha", "surya_caption"],
    center: [27.91, 88.2],
    zoom: 12,
    gsdM: 2.5,
    mapMode: "dem",
    swipeEnabled: true,
    beforeLabel: "Cartosat-3 High-Res DEM",
    afterLabel: "RISAT-1A Moraine Subsidence Rate",
    landcover: "glacial_lake",
    predictedClass: "moraine_dam_breach",
    slopeOverride: 28.4,
    samples: [
      { lang: "en", text: "Assess moraine dam stability and GLOF flood corridor at South Lhonak lake" },
      { lang: "hi", text: "दक्षिण ल्होनक झील में ग्लेशियर टूटने और बाढ़ का खतरा नापो" },
      { lang: "ne", text: "दक्षिण ल्होनक ताल फुट्ने सम्भावना र बाढी जोखिम नक्साङ्कन गर्नुहोस्" },
    ],
    geojson: fc([
      poly(
        [
          [88.16, 27.89],
          [88.23, 27.88],
          [88.25, 27.93],
          [88.18, 27.94],
        ],
        { kind: "lake", name: "South Lhonak Proglacial Lake", value: 1.82, unit: "km²" },
      ),
      poly(
        [
          [88.2, 27.9],
          [88.24, 27.89],
          [88.23, 27.92],
          [88.19, 27.92],
        ],
        { kind: "hazard", name: "Moraine dam lateral deformation", value: 0.44, unit: "km²" },
      ),
      line(
        [
          [88.22, 27.89],
          [88.35, 27.75],
          [88.58, 27.6],
        ],
        { kind: "flood_path", name: "Downstream Teesta flash flood corridor", value: 42, unit: "km alert axis" },
      ),
      point([88.62, 27.6], { kind: "infrastructure", name: "Chungthang Dam (Teesta-III)", value: 1200, unit: "MW" }),
      point([88.55, 27.48], { kind: "infrastructure", name: "Dikchu Suspension Bridge", value: 1, unit: "critical link" }),
    ]),
    geocp: {
      ece: 0.019,
      coverage: 0.973,
      moranI: 0.38,
      interval: [1.8, 3.4],
      zone: "High-Altitude Glaciated Cryosphere",
    },
    answer:
      "South Lhonak proglacial lake volume has expanded to 1.82 km² with moraine dam displacement of 3.4 cm/month. Immediate downstream Teesta cascade warning issued.",
    vqa: {
      question: "Is the South Lhonak moraine dam structurally compromised?",
      answer: "Yes. DInSAR interferometry detects 3.4 cm/month crest displacement with 28.4° frontal slope.",
      confidence: 0.976,
    },
    report: {
      t1: "High-priority GLOF warning: South Lhonak Lake (elevation 5,200 m) shows critical moraine dam lateral deformation with a 42 km downstream impact corridor.",
      t2: "NDMA SOP: Immediate pre-emptive spillway draw-down at Chungthang Teesta-III dam. Evacuate low-lying settlements along Lachen, Chungthang, and Singtam within 35 minutes.",
      t3: "Ratna-Garbha + Kaal-Radar multi-temporal DInSAR reveals 3.4 cm/month moraine ridge subsidence. Cartosat-3 sub-meter DEM verifies 28.4° down-valley slope gradient. Hydrodynamic breach simulation projects 8,400 m³/s peak surge.",
      t4: [
        { label: "Lake Area", value: "1.82 km²" },
        { label: "Moraine Slip", value: "3.4 cm/mo" },
        { label: "Frontal Slope", value: "28.4°" },
        { label: "Impact Corridor", value: "42 km Teesta" },
        { label: "Lead Time", value: "35 min" },
      ],
    },
    ndmaSop:
      "[NDMA-SOP-2026/SK-05] SIKKIM STATE DISASTER MANAGEMENT AUTHORITY\n1. Sound red siren alert across Chungthang, Mangan, and Dikchu river basins.\n2. Open all radial gates of Teesta-III Chungthang Dam to drain reservoir capacity to minimum operating level.\n3. Evacuate ITBP border posts and NH-10 riverbed transit camps to ridge tops.\n4. Stand by NDRF 2nd Battalion at Pakyong Airfield for rotary-wing air extraction.",
  },
  {
    id: "delhi_thermal",
    code: "DL-AQ-03",
    title: "Delhi-NCR Stubble Fire & Inversion",
    region: "Indo-Gangetic Plain · NCR / Punjab",
    problem: "Post-harvest paddy residue combustion trapped beneath low nocturnal atmospheric boundary layer.",
    agent: "bhoomi_optical",
    secondaryAgents: ["kala_chakra", "surya_caption", "sparsh_grounding"],
    center: [28.65, 77.15],
    zoom: 10,
    gsdM: 15,
    mapMode: "optical",
    swipeEnabled: true,
    beforeLabel: "AWiFS Surface Albedo",
    afterLabel: "TRISHNA 8-Band Thermal IR LST (+12K)",
    landcover: "urban_thermal",
    predictedClass: "thermal_anomaly",
    slopeOverride: 1.2,
    samples: [
      { lang: "en", text: "Track stubble fire thermal anomalies and plume dispersion across Delhi-NCR" },
      { lang: "hi", text: "दिल्ली-एनसीआर में पराली के हॉटस्पॉट और थर्मल इन्वर्जन का धुआं दिखाओ" },
      { lang: "pa", text: "ਦਿੱਲੀ-ਐਨਸੀਆਰ ਵਿੱਚ ਪਰਾਲੀ ਦੇ ਧੂੰਏਂ ਅਤੇ ਥਰਮਲ ਹੌਟਸਪੌਟ ਦੀ ਜਾਂਚ ਕਰੋ" },
    ],
    geojson: fc([
      poly(
        [
          [76.75, 28.35],
          [77.45, 28.3],
          [77.55, 28.95],
          [76.85, 28.98],
        ],
        { kind: "plume", name: "Atmospheric thermal inversion plume", value: 2840, unit: "km²" },
      ),
      poly(
        [
          [76.88, 28.85],
          [77.12, 28.82],
          [77.15, 29.1],
          [76.9, 29.12],
        ],
        { kind: "hotspot", name: "Active agricultural fire cluster", value: 186, unit: "hotspots" },
      ),
      line(
        [
          [76.95, 28.9],
          [77.1, 28.75],
          [77.22, 28.62],
        ],
        { kind: "trajectory", name: "NW wind dispersion trajectory (3.2 m/s)", value: 48, unit: "km" },
      ),
      point([77.31, 28.65], { kind: "station", name: "Anand Vihar CAAQMS", value: 482, unit: "µg/m³ PM2.5" }),
      point([77.1, 28.56], { kind: "station", name: "IGI Airport Runway", value: 350, unit: "m visibility" }),
    ]),
    geocp: {
      ece: 0.024,
      coverage: 0.958,
      moranI: 0.62,
      interval: [0.78, 0.95],
      zone: "Indo-Gangetic Basin · Atmospheric",
    },
    answer:
      "TRISHNA 8-band thermal IR detects 186 active fire hotspots (FRP 4.8 GW) in Sonipat-Panipat corridor. NW vector (3.2 m/s) transports 2,840 km² smoke plume directly into Delhi-NCR basin under a 280 m inversion cap.",
    vqa: {
      question: "What is the primary driver of the air quality emergency in NCR?",
      answer: "186 upwind fire hotspots trapped by nocturnal thermal inversion at 280 m boundary layer.",
      confidence: 0.982,
    },
    report: {
      t1: "Severe episodic air pollution event across Delhi-NCR. TRISHNA thermal telemetry maps 186 active crop residue combustion clusters with an aggregate 2,840 km² smoke inversion footprint.",
      t2: "NDMA / CAQM Directive: Enforce GRAP Stage-IV emergency restrictions across NCR. Halt non-essential diesel trucking, suspend construction, and deploy high-capacity anti-smog water cannons along ring road corridors.",
      t3: "Bhoomi-Optical + TRISHNA LST split-window inversion indicates hotspot surface temperature differential ΔT > +12.4 K above baseline. Kala-Chakra-4D spatio-temporal wind advection matches PM2.5 surge with 4.5 h lag from upwind fields.",
      t4: [
        { label: "Active Fires", value: "186 clusters" },
        { label: "Fire Radiative Power", value: "4.8 GW" },
        { label: "Plume Area", value: "2,840 km²" },
        { label: "Inversion Cap", value: "280 m MSL" },
        { label: "PM2.5 Peak", value: "482 µg/m³" },
      ],
    },
    ndmaSop:
      "[CAQM/GRAP-IV/DL-03] COMMISSION FOR AIR QUALITY MANAGEMENT IN NCR\n1. Implement GRAP Stage-IV with immediate effect across Delhi, Gurugram, Faridabad, Ghaziabad, and Noida.\n2. Ban entry of non-BS VI diesel commercial heavy goods vehicles into NCT of Delhi.\n3. Mandate 50% work-from-home across public and private sector offices.\n4. Direct district magistrates in Punjab/Haryana to mobilize agricultural nodal officers with zero-till happy-seeders to suppress fresh burning.",
  },
  {
    id: "rajasthan_mineral",
    code: "RJ-MN-12",
    title: "Aravalli Rare-Earth & Lithium Pegmatite",
    region: "Rajasthan · Nagaur & Aravalli Belt",
    problem: "Sub-surface rare-earth greisen and lithium pegmatite veins requiring hyperspectral endmember SAM unmixing.",
    agent: "ratna_garbha",
    secondaryAgents: ["bhoomi_optical", "surya_caption", "sparsh_grounding"],
    center: [26.88, 74.32],
    zoom: 12,
    gsdM: 5,
    mapMode: "optical",
    swipeEnabled: false,
    landcover: "arid_mineral",
    predictedClass: "pegmatite_greisen",
    slopeOverride: 6.8,
    samples: [
      { lang: "en", text: "Map lithium-bearing pegmatite and rare-earth veins in Degana tungsten belt" },
      { lang: "hi", text: "डेगाना अरावली बेल्ट में लीथियम और दुर्लभ खनिज नसों की पहचान करो" },
      { lang: "gu", text: "રાજસ્થાન દેગાના પટ્ટામાં લિથિયમ અને ખનિજ ભંડાર ઓળખો" },
    ],
    geojson: fc([
      poly(
        [
          [74.28, 26.84],
          [74.36, 26.83],
          [74.37, 26.91],
          [74.29, 26.92],
        ],
        { kind: "mineral", name: "Greisenized granite anomaly (Al-OH 2.2µm)", value: 34.2, unit: "km²" },
      ),
      poly(
        [
          [74.31, 26.86],
          [74.34, 26.85],
          [74.35, 26.89],
          [74.32, 26.9],
        ],
        { kind: "core_target", name: "High-grade lithium pegmatite body", value: 8.4, unit: "km²" },
      ),
      line(
        [
          [74.25, 26.8],
          [74.35, 26.88],
          [74.45, 26.96],
        ],
        { kind: "fault", name: "Aravalli structural shear zone", value: 18.6, unit: "km strike" },
      ),
      point([74.33, 26.87], { kind: "gsi_point", name: "Degana Old Pit Head", value: 5.4, unit: "Mt inferred ore" }),
      point([74.29, 26.89], { kind: "gsi_point", name: "Sewariya Pegmatite Node", value: 1.2, unit: "% Li2O avg" }),
    ]),
    geocp: {
      ece: 0.016,
      coverage: 0.978,
      moranI: 0.26,
      interval: [0.89, 0.99],
      zone: "Arid Shield & Metamorphic Greisen",
    },
    answer:
      "HyIS 200-band hyperspectral SAM inversion identifies 34.2 km² greisenized zone with 8.4 km² core lithium spodumene concentration along the Degana shear axis.",
    vqa: {
      question: "Are there confirmed spectral signatures of lithium pegmatite in the Degana sector?",
      answer: "Yes. Al-OH absorption doublet at 2.20 µm and Li-bearing mica spectra confirmed with SAM θ < 0.06 rad.",
      confidence: 0.979,
    },
    report: {
      t1: "Strategic Mineral Exploration Brief: High-confidence lithium-cesium-tantalum (LCT) pegmatite complex mapped in the Degana-Sewariya belt of Rajasthan.",
      t2: "GSI / Ministry of Mines Protocol: Recommended for G2-level exploratory diamond core drilling. High-priority auction block demarcation under Critical Minerals Mission 2026.",
      t3: "Ratna-Garbha Hyperspectral Inversion: 224-band AVIRIS-NG / HyIS data processed via Spectral Angle Mapper (SAM) against USGS reference libraries. Narrow Al-OH absorption doublet (2.195–2.208 µm) indicates intense zinnwaldite-muscovite greisenization.",
      t4: [
        { label: "Exploration Target", value: "34.2 km²" },
        { label: "Core Spodumene", value: "8.4 km²" },
        { label: "Avg Grade Est.", value: "1.2% Li2O" },
        { label: "Spectral Angle", value: "θ = 0.058 rad" },
        { label: "Strategic Priority", value: "Category 1" },
      ],
    },
    ndmaSop:
      "[GSI-SOP-2026/RJ-12] GEOLOGICAL SURVEY OF INDIA & MINISTRY OF MINES\n1. Demarcate 34.2 km² reconnaissance exploration perimeter across Degana Tehsil, Nagaur District.\n2. Mobilize 4 GSI multi-rig diamond core exploration units to verify subsurface pegmatite strike to 300 m depth.\n3. Integrate gravity-magnetic telemetry with AVIRIS-NG spectral anomalies for 3D block ore volume inversion.\n4. Prepare Preliminary Exploration Report (G3 level) for Union Ministry auction under Mines & Minerals (Development & Regulation) Act.",
  },
];

export const MISSION_BY_ID = Object.fromEntries(MISSIONS.map((m) => [m.id, m])) as Record<
  Mission["id"],
  Mission
>;
